name: Publish

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7' 
    - name: Set up mpkg
      env:
        repo: ${{ github.repository }}
      run: |
        pip install git+https://github.com/mpkg-project/mpkg.git -q
        #pip install mpkg==0.0.6
        python3 main.py
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if [ -n "$(git status -s)" ]; then git commit -m "$(date +%y%m%d)"; fi
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
